# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8c70a02d20b8bf44d2187a6e73eef9e7151c7f67c24cc393d99e2dbb6989f3bafd8929109caa5b6027c82deaec5e59dccecd5f895012e114bd485345218f8a7a

test:
  secret_key_base: 6bff342b099aaec30f10b19ffb02c636a6be220dc548d784be4fe0db9cff2aa6a713031316ccfdd81587cbe7866f29686de2d74c235366aa9e46f45f9948da12

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
